//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Onlajjn_magazin
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ тапочек.
    /// </summary>
    // *** Start programmer edit section *** (ЗаказТапочек CustomAttributes)

    // *** End programmer edit section *** (ЗаказТапочек CustomAttributes)
    [AutoAltered()]
    [Caption("Заказ тапочек")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказТапочекE", new string[] {
            "Комментарий as \'Комментарий\'",
            "Тапочки as \'Тапочки\'",
            "Тапочки.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Тапочки.Наименование"})]
    [MasterViewDefineAttribute("ЗаказТапочекE", "Тапочки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ЗаказТапочек : ICSSoft.STORMNET.DataObject
    {
        
        private string fКомментарий;
        
        private IIS.Onlajjn_magazin.Тапочки fТапочки;
        
        private IIS.Onlajjn_magazin.Заказы fЗаказы;
        
        // *** Start programmer edit section *** (ЗаказТапочек CustomMembers)

        // *** End programmer edit section *** (ЗаказТапочек CustomMembers)

        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказТапочек.Комментарий CustomAttributes)

        // *** End programmer edit section *** (ЗаказТапочек.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказТапочек.Комментарий Get start)

                // *** End programmer edit section *** (ЗаказТапочек.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (ЗаказТапочек.Комментарий Get end)

                // *** End programmer edit section *** (ЗаказТапочек.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказТапочек.Комментарий Set start)

                // *** End programmer edit section *** (ЗаказТапочек.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (ЗаказТапочек.Комментарий Set end)

                // *** End programmer edit section *** (ЗаказТапочек.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// Заказ тапочек.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказТапочек.Тапочки CustomAttributes)

        // *** End programmer edit section *** (ЗаказТапочек.Тапочки CustomAttributes)
        [PropertyStorage(new string[] {
                "Тапочки"})]
        [NotNull()]
        public virtual IIS.Onlajjn_magazin.Тапочки Тапочки
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказТапочек.Тапочки Get start)

                // *** End programmer edit section *** (ЗаказТапочек.Тапочки Get start)
                IIS.Onlajjn_magazin.Тапочки result = this.fТапочки;
                // *** Start programmer edit section *** (ЗаказТапочек.Тапочки Get end)

                // *** End programmer edit section *** (ЗаказТапочек.Тапочки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказТапочек.Тапочки Set start)

                // *** End programmer edit section *** (ЗаказТапочек.Тапочки Set start)
                this.fТапочки = value;
                // *** Start programmer edit section *** (ЗаказТапочек.Тапочки Set end)

                // *** End programmer edit section *** (ЗаказТапочек.Тапочки Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Onlajjn_magazin.Заказы.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказТапочек.Заказы CustomAttributes)

        // *** End programmer edit section *** (ЗаказТапочек.Заказы CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Заказы"})]
        public virtual IIS.Onlajjn_magazin.Заказы Заказы
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказТапочек.Заказы Get start)

                // *** End programmer edit section *** (ЗаказТапочек.Заказы Get start)
                IIS.Onlajjn_magazin.Заказы result = this.fЗаказы;
                // *** Start programmer edit section *** (ЗаказТапочек.Заказы Get end)

                // *** End programmer edit section *** (ЗаказТапочек.Заказы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказТапочек.Заказы Set start)

                // *** End programmer edit section *** (ЗаказТапочек.Заказы Set start)
                this.fЗаказы = value;
                // *** Start programmer edit section *** (ЗаказТапочек.Заказы Set end)

                // *** End programmer edit section *** (ЗаказТапочек.Заказы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказТапочекE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказТапочекE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказТапочекE", typeof(IIS.Onlajjn_magazin.ЗаказТапочек));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗаказТапочек.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗаказТапочек CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗаказТапочек CustomAttributes)
    public class DetailArrayOfЗаказТапочек : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Onlajjn_magazin.DetailArrayOfЗаказТапочек members)

        // *** End programmer edit section *** (IIS.Onlajjn_magazin.DetailArrayOfЗаказТапочек members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗаказТапочек by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗаказТапочек.
        /// </summary>
        public DetailArrayOfЗаказТапочек(IIS.Onlajjn_magazin.Заказы fЗаказы) : 
                base(typeof(ЗаказТапочек), ((ICSSoft.STORMNET.DataObject)(fЗаказы)))
        {
        }
        
        public IIS.Onlajjn_magazin.ЗаказТапочек this[int index]
        {
            get
            {
                return ((IIS.Onlajjn_magazin.ЗаказТапочек)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Onlajjn_magazin.ЗаказТапочек dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
