//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Onlajjn_magazin
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказы.
    /// </summary>
    // *** Start programmer edit section *** (Заказы CustomAttributes)

    // *** End programmer edit section *** (Заказы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказыE", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "Дата as \'Дата\'",
            "ТипОплаты as \'Тип оплаты\'",
            "ТипВручения as \'Тип вручения\'",
            "Колво as \'Колво\'",
            "Комментарий as \'Комментарий\'",
            "Сумма as \'Сумма\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.Фамилия as \'Фамилия\'",
            "Адрес as \'Адрес\'",
            "Адрес.Город as \'Город\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Клиенты.Фамилия",
            "Адрес.Город",
            "Сотрудник.Фамилия"})]
    [AssociatedDetailViewAttribute("ЗаказыE", "ЗаказТапочек", "ЗаказТапочекE", true, "", "Заказ тапочек", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ЗаказыE", "ЗаказСланцев", "ЗаказСланцевE", true, "", "Заказ сланцев", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаказыE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ЗаказыE", "Адрес", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Город")]
    [MasterViewDefineAttribute("ЗаказыE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("ЗаказыL", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "Дата as \'Дата\'",
            "ТипОплаты as \'Тип оплаты\'",
            "ТипВручения as \'Тип вручения\'",
            "Колво as \'Колво\'",
            "Комментарий as \'Комментарий\'",
            "Сумма as \'Сумма\'",
            "Клиенты.Фамилия as \'Фамилия\'",
            "Адрес.Город as \'Город\'",
            "Сотрудник.Фамилия as \'Фамилия\'"})]
    public class Заказы : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодЗаказа;
        
        private System.DateTime fДата;
        
        private IIS.Onlajjn_magazin.ТипОплаты fТипОплаты;
        
        private IIS.Onlajjn_magazin.ТипПолучения fТипВручения;
        
        private int fКолво;
        
        private string fКомментарий;
        
        private double fСумма;
        
        private IIS.Onlajjn_magazin.Клиенты fКлиенты;
        
        private IIS.Onlajjn_magazin.Адрес fАдрес;
        
        private IIS.Onlajjn_magazin.Сотрудник fСотрудник;
        
        private IIS.Onlajjn_magazin.DetailArrayOfЗаказСланцев fЗаказСланцев;
        
        private IIS.Onlajjn_magazin.DetailArrayOfЗаказТапочек fЗаказТапочек;
        
        // *** Start programmer edit section *** (Заказы CustomMembers)

        // *** End programmer edit section *** (Заказы CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Дата CustomAttributes)

        // *** End programmer edit section *** (Заказы.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Дата Get start)

                // *** End programmer edit section *** (Заказы.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Заказы.Дата Get end)

                // *** End programmer edit section *** (Заказы.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Дата Set start)

                // *** End programmer edit section *** (Заказы.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Заказы.Дата Set end)

                // *** End programmer edit section *** (Заказы.Дата Set end)
            }
        }
        
        /// <summary>
        /// КодЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.КодЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказы.КодЗаказа CustomAttributes)
        public virtual int КодЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.КодЗаказа Get start)

                // *** End programmer edit section *** (Заказы.КодЗаказа Get start)
                int result = this.fКодЗаказа;
                // *** Start programmer edit section *** (Заказы.КодЗаказа Get end)

                // *** End programmer edit section *** (Заказы.КодЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.КодЗаказа Set start)

                // *** End programmer edit section *** (Заказы.КодЗаказа Set start)
                this.fКодЗаказа = value;
                // *** Start programmer edit section *** (Заказы.КодЗаказа Set end)

                // *** End programmer edit section *** (Заказы.КодЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Колво.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Колво CustomAttributes)

        // *** End programmer edit section *** (Заказы.Колво CustomAttributes)
        public virtual int Колво
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Колво Get start)

                // *** End programmer edit section *** (Заказы.Колво Get start)
                int result = this.fКолво;
                // *** Start programmer edit section *** (Заказы.Колво Get end)

                // *** End programmer edit section *** (Заказы.Колво Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Колво Set start)

                // *** End programmer edit section *** (Заказы.Колво Set start)
                this.fКолво = value;
                // *** Start programmer edit section *** (Заказы.Колво Set end)

                // *** End programmer edit section *** (Заказы.Колво Set end)
            }
        }
        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Комментарий CustomAttributes)

        // *** End programmer edit section *** (Заказы.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Комментарий Get start)

                // *** End programmer edit section *** (Заказы.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (Заказы.Комментарий Get end)

                // *** End programmer edit section *** (Заказы.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Комментарий Set start)

                // *** End programmer edit section *** (Заказы.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (Заказы.Комментарий Set end)

                // *** End programmer edit section *** (Заказы.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Сумма CustomAttributes)

        // *** End programmer edit section *** (Заказы.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Сумма Get start)

                // *** End programmer edit section *** (Заказы.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Заказы.Сумма Get end)

                // *** End programmer edit section *** (Заказы.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Сумма Set start)

                // *** End programmer edit section *** (Заказы.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Заказы.Сумма Set end)

                // *** End programmer edit section *** (Заказы.Сумма Set end)
            }
        }
        
        /// <summary>
        /// ТипВручения.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.ТипВручения CustomAttributes)

        // *** End programmer edit section *** (Заказы.ТипВручения CustomAttributes)
        public virtual IIS.Onlajjn_magazin.ТипПолучения ТипВручения
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.ТипВручения Get start)

                // *** End programmer edit section *** (Заказы.ТипВручения Get start)
                IIS.Onlajjn_magazin.ТипПолучения result = this.fТипВручения;
                // *** Start programmer edit section *** (Заказы.ТипВручения Get end)

                // *** End programmer edit section *** (Заказы.ТипВручения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.ТипВручения Set start)

                // *** End programmer edit section *** (Заказы.ТипВручения Set start)
                this.fТипВручения = value;
                // *** Start programmer edit section *** (Заказы.ТипВручения Set end)

                // *** End programmer edit section *** (Заказы.ТипВручения Set end)
            }
        }
        
        /// <summary>
        /// ТипОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.ТипОплаты CustomAttributes)

        // *** End programmer edit section *** (Заказы.ТипОплаты CustomAttributes)
        public virtual IIS.Onlajjn_magazin.ТипОплаты ТипОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.ТипОплаты Get start)

                // *** End programmer edit section *** (Заказы.ТипОплаты Get start)
                IIS.Onlajjn_magazin.ТипОплаты result = this.fТипОплаты;
                // *** Start programmer edit section *** (Заказы.ТипОплаты Get end)

                // *** End programmer edit section *** (Заказы.ТипОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.ТипОплаты Set start)

                // *** End programmer edit section *** (Заказы.ТипОплаты Set start)
                this.fТипОплаты = value;
                // *** Start programmer edit section *** (Заказы.ТипОплаты Set end)

                // *** End programmer edit section *** (Заказы.ТипОплаты Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Адрес CustomAttributes)

        // *** End programmer edit section *** (Заказы.Адрес CustomAttributes)
        [PropertyStorage(new string[] {
                "Адрес"})]
        [NotNull()]
        public virtual IIS.Onlajjn_magazin.Адрес Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Адрес Get start)

                // *** End programmer edit section *** (Заказы.Адрес Get start)
                IIS.Onlajjn_magazin.Адрес result = this.fАдрес;
                // *** Start programmer edit section *** (Заказы.Адрес Get end)

                // *** End programmer edit section *** (Заказы.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Адрес Set start)

                // *** End programmer edit section *** (Заказы.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Заказы.Адрес Set end)

                // *** End programmer edit section *** (Заказы.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Клиенты CustomAttributes)

        // *** End programmer edit section *** (Заказы.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Onlajjn_magazin.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Клиенты Get start)

                // *** End programmer edit section *** (Заказы.Клиенты Get start)
                IIS.Onlajjn_magazin.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (Заказы.Клиенты Get end)

                // *** End programmer edit section *** (Заказы.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Клиенты Set start)

                // *** End programmer edit section *** (Заказы.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (Заказы.Клиенты Set end)

                // *** End programmer edit section *** (Заказы.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Заказы.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Onlajjn_magazin.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Сотрудник Get start)

                // *** End programmer edit section *** (Заказы.Сотрудник Get start)
                IIS.Onlajjn_magazin.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Заказы.Сотрудник Get end)

                // *** End programmer edit section *** (Заказы.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Сотрудник Set start)

                // *** End programmer edit section *** (Заказы.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Заказы.Сотрудник Set end)

                // *** End programmer edit section *** (Заказы.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.ЗаказСланцев CustomAttributes)

        // *** End programmer edit section *** (Заказы.ЗаказСланцев CustomAttributes)
        public virtual IIS.Onlajjn_magazin.DetailArrayOfЗаказСланцев ЗаказСланцев
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.ЗаказСланцев Get start)

                // *** End programmer edit section *** (Заказы.ЗаказСланцев Get start)
                if ((this.fЗаказСланцев == null))
                {
                    this.fЗаказСланцев = new IIS.Onlajjn_magazin.DetailArrayOfЗаказСланцев(this);
                }
                IIS.Onlajjn_magazin.DetailArrayOfЗаказСланцев result = this.fЗаказСланцев;
                // *** Start programmer edit section *** (Заказы.ЗаказСланцев Get end)

                // *** End programmer edit section *** (Заказы.ЗаказСланцев Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.ЗаказСланцев Set start)

                // *** End programmer edit section *** (Заказы.ЗаказСланцев Set start)
                this.fЗаказСланцев = value;
                // *** Start programmer edit section *** (Заказы.ЗаказСланцев Set end)

                // *** End programmer edit section *** (Заказы.ЗаказСланцев Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.ЗаказТапочек CustomAttributes)

        // *** End programmer edit section *** (Заказы.ЗаказТапочек CustomAttributes)
        public virtual IIS.Onlajjn_magazin.DetailArrayOfЗаказТапочек ЗаказТапочек
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.ЗаказТапочек Get start)

                // *** End programmer edit section *** (Заказы.ЗаказТапочек Get start)
                if ((this.fЗаказТапочек == null))
                {
                    this.fЗаказТапочек = new IIS.Onlajjn_magazin.DetailArrayOfЗаказТапочек(this);
                }
                IIS.Onlajjn_magazin.DetailArrayOfЗаказТапочек result = this.fЗаказТапочек;
                // *** Start programmer edit section *** (Заказы.ЗаказТапочек Get end)

                // *** End programmer edit section *** (Заказы.ЗаказТапочек Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.ЗаказТапочек Set start)

                // *** End programmer edit section *** (Заказы.ЗаказТапочек Set start)
                this.fЗаказТапочек = value;
                // *** Start programmer edit section *** (Заказы.ЗаказТапочек Set end)

                // *** End programmer edit section *** (Заказы.ЗаказТапочек Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказыE", typeof(IIS.Onlajjn_magazin.Заказы));
                }
            }
            
            /// <summary>
            /// "ЗаказыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказыL", typeof(IIS.Onlajjn_magazin.Заказы));
                }
            }
        }
    }
}
