//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Onlajjn_magazin
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ сланцев.
    /// </summary>
    // *** Start programmer edit section *** (ЗаказСланцев CustomAttributes)

    // *** End programmer edit section *** (ЗаказСланцев CustomAttributes)
    [AutoAltered()]
    [Caption("Заказ сланцев")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказСланцевE", new string[] {
            "Комментарий as \'Комментарий\'",
            "Сланцы as \'Сланцы\'",
            "Сланцы.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Сланцы.Наименование"})]
    [MasterViewDefineAttribute("ЗаказСланцевE", "Сланцы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ЗаказСланцев : ICSSoft.STORMNET.DataObject
    {
        
        private string fКомментарий;
        
        private IIS.Onlajjn_magazin.Сланцы fСланцы;
        
        private IIS.Onlajjn_magazin.Заказы fЗаказы;
        
        // *** Start programmer edit section *** (ЗаказСланцев CustomMembers)

        // *** End programmer edit section *** (ЗаказСланцев CustomMembers)

        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказСланцев.Комментарий CustomAttributes)

        // *** End programmer edit section *** (ЗаказСланцев.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказСланцев.Комментарий Get start)

                // *** End programmer edit section *** (ЗаказСланцев.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (ЗаказСланцев.Комментарий Get end)

                // *** End programmer edit section *** (ЗаказСланцев.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказСланцев.Комментарий Set start)

                // *** End programmer edit section *** (ЗаказСланцев.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (ЗаказСланцев.Комментарий Set end)

                // *** End programmer edit section *** (ЗаказСланцев.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// Заказ сланцев.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказСланцев.Сланцы CustomAttributes)

        // *** End programmer edit section *** (ЗаказСланцев.Сланцы CustomAttributes)
        [PropertyStorage(new string[] {
                "Сланцы"})]
        [NotNull()]
        public virtual IIS.Onlajjn_magazin.Сланцы Сланцы
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказСланцев.Сланцы Get start)

                // *** End programmer edit section *** (ЗаказСланцев.Сланцы Get start)
                IIS.Onlajjn_magazin.Сланцы result = this.fСланцы;
                // *** Start programmer edit section *** (ЗаказСланцев.Сланцы Get end)

                // *** End programmer edit section *** (ЗаказСланцев.Сланцы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказСланцев.Сланцы Set start)

                // *** End programmer edit section *** (ЗаказСланцев.Сланцы Set start)
                this.fСланцы = value;
                // *** Start programmer edit section *** (ЗаказСланцев.Сланцы Set end)

                // *** End programmer edit section *** (ЗаказСланцев.Сланцы Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Onlajjn_magazin.Заказы.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказСланцев.Заказы CustomAttributes)

        // *** End programmer edit section *** (ЗаказСланцев.Заказы CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Заказы"})]
        public virtual IIS.Onlajjn_magazin.Заказы Заказы
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказСланцев.Заказы Get start)

                // *** End programmer edit section *** (ЗаказСланцев.Заказы Get start)
                IIS.Onlajjn_magazin.Заказы result = this.fЗаказы;
                // *** Start programmer edit section *** (ЗаказСланцев.Заказы Get end)

                // *** End programmer edit section *** (ЗаказСланцев.Заказы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказСланцев.Заказы Set start)

                // *** End programmer edit section *** (ЗаказСланцев.Заказы Set start)
                this.fЗаказы = value;
                // *** Start programmer edit section *** (ЗаказСланцев.Заказы Set end)

                // *** End programmer edit section *** (ЗаказСланцев.Заказы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказСланцевE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказСланцевE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказСланцевE", typeof(IIS.Onlajjn_magazin.ЗаказСланцев));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗаказСланцев.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗаказСланцев CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗаказСланцев CustomAttributes)
    public class DetailArrayOfЗаказСланцев : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Onlajjn_magazin.DetailArrayOfЗаказСланцев members)

        // *** End programmer edit section *** (IIS.Onlajjn_magazin.DetailArrayOfЗаказСланцев members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗаказСланцев by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗаказСланцев.
        /// </summary>
        public DetailArrayOfЗаказСланцев(IIS.Onlajjn_magazin.Заказы fЗаказы) : 
                base(typeof(ЗаказСланцев), ((ICSSoft.STORMNET.DataObject)(fЗаказы)))
        {
        }
        
        public IIS.Onlajjn_magazin.ЗаказСланцев this[int index]
        {
            get
            {
                return ((IIS.Onlajjn_magazin.ЗаказСланцев)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Onlajjn_magazin.ЗаказСланцев dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
