//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Onlajjn_magazin
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// УправляющийОбъект.
    /// </summary>
    // *** Start programmer edit section *** (УправляющийОбъект CustomAttributes)

    // *** End programmer edit section *** (УправляющийОбъект CustomAttributes)
    public class УправляющийОбъект
    {
        
        private IIS.Onlajjn_magazin.События fСобытия;
        
        // *** Start programmer edit section *** (УправляющийОбъект CustomMembers)

        // *** End programmer edit section *** (УправляющийОбъект CustomMembers)

        
        /// <summary>
        /// УправляющийОбъект.
        /// </summary>
        // *** Start programmer edit section *** (УправляющийОбъект.События CustomAttributes)

        // *** End programmer edit section *** (УправляющийОбъект.События CustomAttributes)
        public virtual IIS.Onlajjn_magazin.События События
        {
            get
            {
                // *** Start programmer edit section *** (УправляющийОбъект.События Get start)

                // *** End programmer edit section *** (УправляющийОбъект.События Get start)
                IIS.Onlajjn_magazin.События result = this.fСобытия;
                // *** Start programmer edit section *** (УправляющийОбъект.События Get end)

                // *** End programmer edit section *** (УправляющийОбъект.События Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УправляющийОбъект.События Set start)

                // *** End programmer edit section *** (УправляющийОбъект.События Set start)
                this.fСобытия = value;
                // *** Start programmer edit section *** (УправляющийОбъект.События Set end)

                // *** End programmer edit section *** (УправляющийОбъект.События Set end)
            }
        }
    }
}
